export const RELATED_MINISTRIES: string[] = [
  "22000 - Ministério da Agricultura e Pecuária",
  "24000 - Ministério da Ciência, Tecnologia e Inovação",
  "26000 - Ministério da Educação",
  "36000 - Ministério da Saúde",
  "38000 - Ministério do Trabalho e Emprego",
  "40000 - Ministério do Trabalho e Emprego",
  "41000 - Ministério das Comunicações",
  "42000 - Ministério da Cultura",
  "44000 - Ministério do Meio Ambiente e Mudança do Clima",
  "49000 - Ministério do Desenvolvimento Agrário e Agricultura Familiar",
  "51000 - Ministério do Esporte",
  "53000 - Ministério da Integração e do Desenvolvimento Regional",
  "54000 - Ministério do Turismo",
  "55000 - Ministério do Desenvolvimento e Assistência Social, Família e Combate à Fome",
  "56000 - Ministério das Cidades",
  "57000 - Ministério das Mulheres, da Igualdade Racial, da Juventude e dos Direitos Humanos",
  "58000 - Ministério da Pesca e Aquicultura",
  "64000 - Ministério dos Direitos Humanos e da Cidadania",
  "65000 - Ministério das Mulheres",
  "67000 - Ministério da Igualdade Racial",
  "69000 - Ministério do Empreendedorismo, da Microempresa e da Empresa de Pequeno Porte",
  "81000 - Ministério dos Direitos Humanos e da Cidadania",
  "84000 - Ministério dos Povos Indígenas"
]; 